const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const pagePath = path.resolve(__dirname, '../regex-tester.html');
const page = fs.existsSync(pagePath) ? fs.readFileSync(pagePath, 'utf8') : '';
const nav = fs.readFileSync(path.resolve(__dirname, '../nav.js'), 'utf8');
const index = fs.readFileSync(path.resolve(__dirname, '../index.html'), 'utf8');

assert.match(nav, /name: '正则测试'/);
assert.match(nav, /path: 'regex-tester\.html'/);
assert.match(index, /href="regex-tester\.html"/);
assert.match(index, /正则表达式测试/);

assert.match(page, /<title>正则表达式测试工具<\/title>/);
assert.match(page, /<link rel="stylesheet" href="nav\.css">/);
assert.match(page, /<script src="nav\.js" defer><\/script>/);
assert.match(page, /<script src="changelog\.js"><\/script>/);
assert.match(page, /<script src="clipboard-utils\.js"><\/script>/);
assert.match(page, /<script src="editor-lines\.js"><\/script>/);
assert.match(page, /<script src="regex-templates\.js"><\/script>/);
assert.match(page, /<script src="regex-runtime-utils\.js"><\/script>/);
assert.match(page, /<script src="regex-risk-analyzer\.js"><\/script>/);
assert.match(page, /<h1>正则表达式测试<\/h1>/);
assert.match(page, /class="version-info" onclick="showChangelog\(\)"/);
assert.match(page, /<span>V1\.10<\/span>/);
assert.match(page, /<h3>🚀 版本更新说明<\/h3>/);
assert.match(page, /<div class="changelog-date">2026年7月2日<\/div>/);
assert.match(page, /<div class="changelog-version">V1\.10<\/div>/);
assert.match(page, /RegexRiskAnalyzer\.analyzeRegexRisks/);
assert.match(page, /<div class="changelog-version">V1\.09<\/div>/);
assert.match(page, /getRegexWithFlags is not defined/);
assert.match(page, /<div class="changelog-version">V1\.08<\/div>/);
assert.match(page, /新增常用正则模板库，可一键填入手机号、URL、JDBC、IP、邮箱、日志时间和异常堆栈示例。/);
assert.match(page, /<div class="changelog-version">V1\.07<\/div>/);
assert.match(page, /优化四种正则可视化视图，支持连续字符合并、字面转义解码和字符集合纵向拆分。/);
assert.match(page, /<div class="changelog-version">V1\.06<\/div>/);
assert.match(page, /新增 Regulex 风格的正则流程图，通过连线、分支、循环和分组框展示正则匹配结构。/);
assert.match(page, /<div class="changelog-date">2026年6月19日<\/div>/);
assert.equal(
  (page.match(/<div class="changelog-date">2026年6月19日<\/div>/g) || []).length,
  1,
);
assert.match(page, /<div class="changelog-version">V1\.05<\/div>/);
assert.match(page, /新增正则表达式可视化，支持匹配路径图、语法树和分段说明三种视图，并提供实时解析与错误定位。/);
assert.match(page, /<div class="changelog-version">V1\.04<\/div>/);
assert.match(page, /<div class="changelog-desc">兼容从配置或代码中复制出来的双反斜杠转义正则，避免 <code>\\\\s<\/code> 这类写法截断匹配结果。<\/div>/);
assert.match(page, /<div class="changelog-version">V1\.03<\/div>/);
assert.match(page, /<div class="changelog-desc">兼容 \(\?i\) 前缀标志，初始化自动生成替换结果，并在高亮预览中标出捕获分组。<\/div>/);
assert.match(page, /<div class="changelog-version">V1\.02<\/div>/);
assert.match(page, /<div class="changelog-desc">优化正则测试布局、测试内容行号、匹配结果行列定位和替换文本示例说明。<\/div>/);
assert.match(page, /<div class="changelog-version">V1\.01<\/div>/);
assert.match(page, /<div class="changelog-version">V1\.00<\/div>/);

assert.match(page, /class="workspace three-column"/);
assert.match(page, /class="panel input-panel"/);
assert.match(page, /class="panel control-panel"/);
assert.match(page, /class="panel output-panel"/);
assert.match(page, /class="editor-with-lines"/);
assert.match(page, /id="testLineNumbers"/);
assert.match(page, /id="testText"/);
assert.match(page, /id="templateSelect"/);
assert.match(page, /id="applyTemplateBtn"[^>]*>应用模板<\/button>/);
assert.match(page, /id="templateDescription"/);
assert.match(page, /id="patternInput"/);
assert.match(page, /id="riskWarning"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(page, /\.risk-warning\s*\{[\s\S]*?display:\s*none/);
assert.match(page, /riskWarning\.className = 'risk-warning show'/);
assert.match(page, /function updateRiskWarning\(\)/);
assert.match(page, /riskWarning\.innerHTML/);
assert.match(page, /高风险正则结构/);
assert.match(page, /nested-quantifier/);
assert.match(page, /overlapping-alternation/);
assert.match(page, /value="\^\(1\[3-9\]\\d\{2\}\)\\d\{3\}\(\\d\{4\}\)\$"/);
assert.match(page, /id="replaceInput"/);
assert.match(page, /value="\$1\*\*\*\$2"/);
assert.match(page, /placeholder="例如：手机号脱敏 \$1\*\*\*\$2"/);
assert.match(page, /title="替换文本示例：&#10;\$1、\$2 表示匹配规则里的第 1、第 2 个括号分组。&#10;当前默认规则会把手机号拆成前 4 位和后 4 位，默认替换文本会输出脱敏手机号。&#10;\$& 表示完整匹配内容，例如把每个手机号替换为【\$&】。&#10;删除匹配内容：替换文本留空即可。"/);
assert.match(page, /id="replaceHint"/);
assert.match(page, /<p class="field-help">[\s\S]*?替换文本是“找到匹配内容后要换成什么”。[\s\S]*?默认示例会把手机号中间 3 位替换成星号[\s\S]*?<code>\$1\*\*\*\$2<\/code>[\s\S]*?<\/p>/);

assert.match(page, /id="matchResult"/);
assert.match(page, /id="replaceResult"/);
assert.match(page, /id="flagGlobal"/);
assert.match(page, /id="flagIgnoreCase"/);
assert.match(page, /id="flagMultiline"/);
assert.match(page, /id="flagDotAll"/);
assert.match(page, /id="flagUnicode"/);
assert.match(page, /data-tooltip="勾选后会找出文本里的全部匹配结果，而不是只找第一个。"/);
assert.match(page, /data-tooltip="勾选后匹配时不区分英文字母大小写。"/);
assert.match(page, /data-tooltip="勾选后可以按每一行单独匹配，适合逐行校验手机号、日志等内容。"/);
assert.match(page, /data-tooltip="勾选后点号可以匹配换行符。"/);
assert.match(page, /data-tooltip="勾选后会按 Unicode 规则识别字符，适合包含中文、表情或特殊字符的文本。"/);
assert.match(page, /<label class="flag-pill" data-tooltip="[^"]+"><input id="flagGlobal" type="checkbox" checked> 查找全部<\/label>/);
assert.match(page, /<label class="flag-pill" data-tooltip="[^"]+"><input id="flagIgnoreCase" type="checkbox"> 忽略大小写<\/label>/);
assert.match(page, /<label class="flag-pill" data-tooltip="[^"]+"><input id="flagMultiline" type="checkbox" checked> 逐行匹配<\/label>/);
assert.match(page, /<label class="flag-pill" data-tooltip="[^"]+"><input id="flagDotAll" type="checkbox"> 点号匹配换行<\/label>/);
assert.match(page, /<label class="flag-pill" data-tooltip="[^"]+"><input id="flagUnicode" type="checkbox"> 识别 Unicode<\/label>/);
assert.doesNotMatch(page, /<label class="flag-pill" title=/);
assert.doesNotMatch(page, /当前标志/);
assert.match(page, /id="testBtn"[^>]*>测试匹配<\/button>/);
assert.match(page, /id="visualizeBtn"[^>]*>正则可视化<\/button>/);
assert.match(page, /id="replaceBtn"[^>]*>执行替换<\/button>/);
assert.match(page, /id="copyMatchBtn"[^>]*>复制匹配结果<\/button>/);
assert.match(page, /id="copyReplaceBtn"[^>]*>复制替换结果<\/button>/);
assert.doesNotMatch(page, /id="loadSampleBtn"/);
assert.doesNotMatch(page, /载入手机号示例/);

const visualizerScriptIndex = page.indexOf('<script src="regex-visualizer.js"></script>');
const displayModelScriptIndex = page.indexOf('<script src="regex-display-model.js"></script>');
const flowLayoutScriptIndex = page.indexOf('<script src="regex-flow-layout.js"></script>');
const runtimeUtilsScriptIndex = page.indexOf('<script src="regex-runtime-utils.js"></script>');
const inlineScriptIndex = page.indexOf('<script>');
assert.notEqual(visualizerScriptIndex, -1);
assert.notEqual(displayModelScriptIndex, -1);
assert.notEqual(flowLayoutScriptIndex, -1);
assert.notEqual(runtimeUtilsScriptIndex, -1);
assert.ok(visualizerScriptIndex < inlineScriptIndex);
assert.ok(visualizerScriptIndex < flowLayoutScriptIndex);
assert.ok(visualizerScriptIndex < displayModelScriptIndex);
assert.ok(displayModelScriptIndex < flowLayoutScriptIndex);
assert.ok(flowLayoutScriptIndex < inlineScriptIndex);
assert.ok(flowLayoutScriptIndex < runtimeUtilsScriptIndex);
assert.ok(runtimeUtilsScriptIndex < inlineScriptIndex);

assert.match(page, /id="regex-visualizer-modal"[^>]*class="modal-overlay"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-labelledby="visualizerTitle"[^>]*aria-hidden="true"/);
assert.match(page, /class="modal-content visualizer-dialog"/);
assert.match(page, /id="visualizerTitle"[^>]*>正则表达式可视化<\/h3>/);
assert.match(page, /id="closeVisualizerBtn"/);
assert.match(page, /class="visualizer-source"[\s\S]*?原始正则表达式[\s\S]*?id="visualizerSource"/);
assert.match(page, /id="flowDiagramTab"[^>]*role="tab"[^>]*data-view="flowDiagram"[^>]*class="visualizer-tab active"[^>]*aria-selected="true"[^>]*aria-controls="flowDiagramView"[^>]*tabindex="0"[^>]*>正则流程图<\/button>/);
assert.match(page, /id="railroadTab"[^>]*role="tab"[^>]*data-view="railroad"[^>]*class="visualizer-tab"[^>]*aria-selected="false"[^>]*aria-controls="railroadView"[^>]*tabindex="-1"[^>]*>匹配路径图<\/button>/);
assert.ok(page.indexOf('id="flowDiagramTab"') < page.indexOf('id="railroadTab"'));
assert.match(page, /id="treeTab"[^>]*role="tab"[^>]*data-view="tree"[^>]*class="visualizer-tab"[^>]*aria-selected="false"[^>]*aria-controls="treeView"[^>]*tabindex="-1"[^>]*>语法树<\/button>/);
assert.match(page, /id="explanationTab"[^>]*role="tab"[^>]*data-view="explanation"[^>]*class="visualizer-tab"[^>]*aria-selected="false"[^>]*aria-controls="explanationView"[^>]*tabindex="-1"[^>]*>分段说明<\/button>/);
assert.match(page, /id="visualizerError"[^>]*aria-live="polite"/);
assert.match(page, /id="flowDiagramView"[^>]*class="visualizer-view active"[^>]*role="tabpanel"[^>]*aria-labelledby="flowDiagramTab"(?![^>]*\shidden(?:\s|>|=))/);
assert.match(page, /id="railroadView"[^>]*class="visualizer-view"[^>]*role="tabpanel"[^>]*aria-labelledby="railroadTab"[^>]*hidden/);
assert.match(page, /id="treeView"[^>]*class="visualizer-view"[^>]*role="tabpanel"[^>]*aria-labelledby="treeTab"[^>]*hidden/);
assert.match(page, /id="explanationView"[^>]*class="visualizer-view"[^>]*role="tabpanel"[^>]*aria-labelledby="explanationTab"[^>]*hidden/);

assert.match(page, /\.visualizer-dialog\s*\{[\s\S]*?width:\s*min\(1400px,\s*calc\(100vw - 48px\)\)[\s\S]*?max-height:\s*calc\(100vh - 48px\)/);
assert.match(page, /\.visualizer-body\s*\{[\s\S]*?overflow:\s*auto/);
assert.match(page, /\.visualizer-view\s*\{[\s\S]*?overflow:\s*auto/);
assert.match(page, /\.visualizer-tabs\s*\{[\s\S]*?overflow-x:\s*auto/);
assert.match(page, /\.visualizer-source\s*\{[\s\S]*?grid-template-columns:\s*auto minmax\(0,\s*1fr\)/);
assert.match(page, /\.railroad-/);
assert.match(page, /\.syntax-tree/);
assert.match(page, /\.explanation-table/);
assert.match(page, /@media \(max-width: 640px\)[\s\S]*?\.visualizer-dialog\s*\{[\s\S]*?width:\s*calc\(100vw - 16px\)[\s\S]*?max-height:\s*calc\(100vh - 16px\)/);

assert.match(page, /function updateLineNumbers\(\)/);
assert.match(page, /function syncLineNumberScroll\(\)/);
assert.match(page, /function getFlagsForPattern\(pattern\)/);
assert.match(page, /function buildRegex\(\)/);
assert.match(page, /function runMatch\(\)/);
assert.match(page, /function runReplace\(showNotification = true\)/);
assert.match(page, /RegexRuntimeUtils\.parseInlineFlags\(/);
assert.match(page, /RegexRuntimeUtils\.normalizeEscapedRegexPattern\(/);
assert.match(page, /RegexRuntimeUtils\.getRegexWithFlags\(/);
assert.doesNotMatch(page, /globalRegex = getRegexWithFlags\(/);
assert.match(page, /RegexRuntimeUtils\.getLineColumn\(/);
assert.match(page, /RegexRuntimeUtils\.getMissingReplacementGroups\(/);
assert.doesNotMatch(page, /function getLineColumn\(text, index\)/);
assert.doesNotMatch(page, /function parseInlineFlags\(pattern, selectedFlags\)/);
assert.doesNotMatch(page, /function getRegexWithFlags\(source, flags\)/);
assert.doesNotMatch(page, /function normalizeEscapedRegexPattern\(pattern\)/);
assert.doesNotMatch(page, /function getCaptureGroupCount\(/);
assert.doesNotMatch(page, /function getMissingReplacementGroups\(/);
assert.match(page, /function updateReplaceHint\(/);
assert.match(page, /function renderHighlightedText\(/);
assert.match(page, /\.match-group-highlight/);
assert.match(page, /match\.indices/);
assert.match(page, /function describeVisualizerNode\(node\)/);
assert.match(page, /const regexTemplates = RegexTemplates\.templates/);
assert.match(page, /RegexTemplates\.getTemplateById\(templateSelect\.value\)/);
assert.doesNotMatch(page, /const regexTemplates = \[/);
assert.match(page, /function populateTemplateSelect\(\)/);
assert.match(page, /function getSelectedTemplate\(\)/);
assert.match(page, /function setRegexFlags\(flags\)/);
assert.match(page, /function applySelectedTemplate\(\)/);
assert.match(page, /templateSelect\.addEventListener\('change', applySelectedTemplate\)/);
assert.match(page, /getElementById\('applyTemplateBtn'\)\.addEventListener\('click', applySelectedTemplate\)/);
assert.match(page, /populateTemplateSelect\(\)/);
assert.match(page, /function renderRailroadView\(ast\)/);
assert.match(page, /function renderRailroadNode\(node\)/);
assert.match(page, /data-node-raw="\$\{escapeHtml\(node\.raw \|\| ''\)\}"/);
assert.match(page, /function renderSyntaxTree\(ast\)/);
assert.match(page, /function renderTreeNode\(node\)/);
assert.match(page, /function flattenVisualizerNodes\(node,/);
assert.match(page, /function renderExplanationTable\(ast\)/);
assert.match(page, /<th>片段<\/th><th>类型<\/th><th>含义<\/th><th>重复<\/th><th>分组<\/th>/);
assert.match(page, /function renderVisualization\(result, isStale = false\)/);
assert.match(page, /RegexDisplayModel\.createRegexDisplayModel\(result\.ast\)/);
assert.match(page, /renderRailroadView\(displayAst\)/);
assert.match(page, /renderFlowDiagramView\(displayAst\)/);
assert.match(page, /renderSyntaxTree\(displayAst\)/);
assert.match(page, /renderExplanationTable\(displayAst\)/);
assert.match(page, /railroad-character-items/);
assert.match(page, /railroad-character-negated/);
assert.match(page, /character-item-list/);
assert.match(page, /character-item/);
assert.match(page, /flow-negated-label/);
assert.match(page, /node\.displayText/);
assert.match(page, /node\.characterItems/);
assert.match(page, /node\.negated/);
assert.match(page, /<tspan/);
assert.match(page, /function renderFlowDiagramView\(ast\)/);
assert.match(page, /RegexFlowLayout\.layoutRegexFlow\(ast\)/);
assert.match(page, /function renderFlowSvg\(layout\)/);
assert.match(page, /<svg class="regex-flow-svg"/);
assert.match(page, /escapeHtml\(node\.raw/);
assert.doesNotMatch(page, /renderRailroadView\(result\.ast\)/);
assert.doesNotMatch(page, /renderFlowDiagramView\(result\.ast\)/);
assert.doesNotMatch(page, /renderSyntaxTree\(result\.ast\)/);
assert.doesNotMatch(page, /renderExplanationTable\(result\.ast\)/);
assert.match(page, /以下为上一次成功解析结果/);
assert.match(page, /let lastSuccessfulVisualization = null/);
assert.match(page, /let visualizerRefreshTimer = null/);
assert.match(page, /let activeVisualizerView = 'flowDiagram'/);
assert.match(page, /visualizerSource\.textContent = patternInput\.value \|\| '（空）'/);
assert.match(page, /function isVisualizerOpen\(\)/);
assert.match(page, /function scheduleVisualizerRefresh\(\)/);
assert.match(page, /setTimeout\(refreshRegexVisualization, 250\)/);
assert.match(page, /function refreshRegexVisualization\(\)/);
assert.match(page, /RegexVisualizer\.parseRegexVisualization\(/);
assert.match(page, /function showVisualizerError\(result\)/);
assert.match(page, /function openRegexVisualizer\(\)/);
assert.match(page, /function closeRegexVisualizer\(\)/);
assert.match(page, /function activateVisualizerView\(viewName,/);
assert.match(page, /patternInput\.addEventListener\('input', scheduleVisualizerRefresh\)/);
assert.match(page, /control\.addEventListener\('change', scheduleVisualizerRefresh\)/);
assert.match(page, /getElementById\('visualizeBtn'\)\.addEventListener\('click', openRegexVisualizer\)/);
assert.match(page, /getElementById\('closeVisualizerBtn'\)\.addEventListener\('click', closeRegexVisualizer\)/);
assert.match(page, /起始位置: \$\{match\.index\}（第 \$\{position\.line\} 行第 \$\{position\.column\} 列）/);
assert.match(page, /testText\.addEventListener\('input', \(\) => \{/);
assert.match(page, /testText\.addEventListener\('scroll', syncLineNumberScroll\)/);
assert.match(page, /runReplace\(false\)/);

assert.match(page, /<strong>正则表达式测试工具说明：<\/strong>/);
assert.match(page, /用于在多行文本中快速验证正则表达式、预览匹配高亮、查看每条匹配的索引与行列位置，并按替换文本生成替换结果。/);
assert.doesNotMatch(page, /常用标志/);
assert.doesNotMatch(page, /function showChangelog\(\)/);
assert.doesNotMatch(page, /window\.showChangelog = showChangelog/);

const normalizeEscapedRegexPattern = (pattern) => pattern.replace(/\\\\(?=[dDsSwWbBtrnvf0()[\]{}.^$|?*+\\/])/g, '\\');
const jdbcText = `URL: jdbc:mysql://demo.mysql.dbdns.cn:6446/schema?useUnicode=true&characterEncoding=utf8&useSSL=false&connectTimeout=10000&socketTimeout=600000
        user: somdbdev`;
const jdbcPatternCopiedFromConfig = String.raw`(jdbc:mysql://[^,\\s]+|jdbc:postgresql://[^,\\s]+|jdbc:tdsql-mysql://[^,\\s]+|jdbc:postgresql://[^,\\s]+|jdbc:gaussdb://[^,\\s]+|jdbc:opengauss://[^,\\s]+|jdbc:olap://[^,\\s]+|jdbc:oracle:(thin|oci):@[^,\\s]*|jdbc:sqlserver://[^,\\s]+)`;
const jdbcMatch = new RegExp(normalizeEscapedRegexPattern(jdbcPatternCopiedFromConfig), 'gm').exec(jdbcText);
assert.equal(jdbcMatch && jdbcMatch[0], 'jdbc:mysql://demo.mysql.dbdns.cn:6446/schema?useUnicode=true&characterEncoding=utf8&useSSL=false&connectTimeout=10000&socketTimeout=600000');

console.log('regex tester integration passed');
