const assert = require('node:assert/strict');
const { parseSql } = require('../sql-visualizer');
const demo = require('../sql-flow-demo');
const execute = (sql, rows) => demo.run(parseSql(sql), { t: rows });
const result = stages => stages.at(-1).after.map(r => ({ ...r.values }));

const flow = demo.run(parseSql(demo.sampleSql), demo.sampleData);
assert.deepEqual(flow.map(s => s.name), ['FROM','WHERE','GROUP BY','HAVING','SELECT','ORDER BY','LIMIT','RESULT']);
assert.deepEqual(flow.map(s => s.after.length), [6,5,4,3,3,3,2,2]);
assert.deepEqual(result(flow), [{city:'北京',total:450},{city:'杭州',total:360}]);
assert.deepEqual(flow[2].after[0].ids, [1,2]);
assert.deepEqual(flow[1].before[3].ids, [4]);
assert.ok(!flow[1].after.some(r => r.ids.includes(4)));
assert.deepEqual(result(execute('SELECT DISTINCT city FROM t ORDER BY city LIMIT 1 OFFSET 1', [{city:'B'}, {city:'A'}, {city:'B'}])), [{city:'B'}]);
assert.deepEqual(result(execute('SELECT id FROM t WHERE (id >= 2 AND id < 4) OR id = 5', [1,2,3,4,5].map(id=>({id})))), [{id:2},{id:3},{id:5}]);
assert.deepEqual(result(execute('SELECT id FROM t WHERE amount IS NULL', [{id:1,amount:null},{id:2,amount:0}])), [{id:1}]);
assert.deepEqual(result(execute('SELECT COUNT(*) AS n, SUM(amount) AS total FROM t', [])), [{n:0,total:null}]);
assert.deepEqual(result(execute('SELECT city, AVG(amount) AS avg_amount FROM t GROUP BY city HAVING avg_amount > 2', [{city:'A',amount:2},{city:'A',amount:4},{city:'B',amount:null}])), [{city:'A',avg_amount:3}]);
assert.deepEqual(result(execute("SELECT 'COUNT(id)' AS note FROM t", [{id:1},{id:2}])), [{note:'COUNT(id)'},{note:'COUNT(id)'}]);
assert.deepEqual(result(execute('SELECT x.id FROM t x WHERE x.id > 1', [{id:1},{id:2}])), [{'x.id':2}]);
assert.throws(()=>execute('SELECT id FROM t WHERE id = :id',[{id:1}]), /暂不演算/);
assert.throws(()=>execute('SELECT city, SUM(amount) FROM t',[{city:'A',amount:1}]), /GROUP BY/);
assert.throws(()=>execute('SELECT missing FROM t',[{id:1}]), /缺少字段/);
assert.throws(()=>execute('SELECT * FROM t JOIN u ON t.id=u.id',[{id:1}]), /JOIN/);
assert.throws(()=>execute('SELECT id FROM t UNION SELECT id FROM t',[{id:1}]), /UNION/);
assert.throws(()=>execute('SELECT * FROM t',Array.from({length:201},()=>({id:1}))), /200 行/);
assert.throws(()=>execute('SELECT * FROM t',[{id:1},{name:'x'}]), /字段一致/);
assert.equal(demo.compile('NULL = 1 OR 2 = 2')({row:{}}), true);
assert.equal(demo.compile('NULL = 1 AND 2 = 3')({row:{}}), false);
assert.equal(demo.compile('2 OR NULL')({row:{}}), true);
assert.deepEqual(result(execute('SELECT id FROM t WHERE 1', [{id:1}])), [{id:1}]);
console.log('SQL data flow demo stage results and unsupported boundaries passed');
